### ISSUE TITLE
Dragging paths for reordering autons

### ISSUE THREAD

**Issue by gftabor** [wpilibsuite/PathUI#17]
If a path is dragged within its own auton the paths should reorder instead of adding a duplicate path to the auton.

**Comment by SilentWanderer** [comment]
**If a user wants an auton to contain the same path multiple times should we allow that?**
Yes, it's pretty likely that at some point a user might want to run the same path but backwards, etc..

**Should the UI assume they are just trying to reorder instead of add a duplicate path?**
It's definitely more intuitive to drag and drop to reorder instead of duplicate. Maybe duplication could be handled by a copy/paste context menu?

**If a user drags a path from an auton into another auton should it now be contained in both or just the new one?**
Same as above.

**Comment by bradamiller** [comment]
I agree that dragging a path should probably reorder (within an autonomous program). And maybe a modifier key, like ctrl or cmd would make it copy. Or a copy/paste menu.
